# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "ACPSS 2017"
email: "acpss@i3s.unice.fr"
description: "The ACP summer school is held annually all around the world"
baseurl: "/summer2017"
url: "http://school.a4cp.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-45498641-2"
googleAnalyticsSiteUrl: "school.a4cp.org"
siteVerification: "09dcT5bQJVjtMrutt2m_aqR5nS9AZ-_RTscjPHuHF10"

# Organizer Info
organizerName: "ACP"
organizerAlternateName: "Association for Constraint Programming"
organizerDescription: "ACP aims at promoting constraint programming in every aspect of the scientific world, by encouraging its theoretical and practical developments, its teaching in the academic institutions, its adoption in the industrial world, and its use in the the application fields."
organizerEmail: "acpss2017@i3s.unice.fr"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.a4cp.org/"

# Head
metaKeywords: "event, summer school, constraint programming, operational research"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: ""
c4sponsorsUrl: "/partnership/"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/diy/", text: "Do It Yourself!"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Buy tickets"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Joint ACP and GdR RO Summer School 2017</br><typeout>"
eventDate: "September 18-22,  2017"
typeoutTextValues: '"", "Constraint Programming", "Operational Research", "Porquerolles, France"'
typeoutFallback: "Constraint Programming"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}
 - {permalink: "/partnership/", text: "Become a sponsor"}
# About Block
aboutTitle: "About the summer school"
aboutBlock:
 - {title: "Topic", image: "OR.jpg", text: "Hybridization of Constraint Programming and Operational Research: from practical opportunities to concrete implementation of solutions." }
# http://sdymchenko.com/blog/2015/03/13/electrifying-eclipse/ 
 - {title: "For which?", image: "electrifying.gif", text: "PhD students, masters students and industrial practitioners, who want to get a good understanding of capabilities and current research directions in the area of Constraint Programming, particularly at the frontier with Operational Research, are all welcome." }
 - {title: "Do it yourself!", image: "minicp.png", text: "minicp competition! The participants will be challenged on a given problem both in term of modeling and implementation of a solution in their own standalone tool." }
 - {title: "1 Place to Go", image: "porquerolles.jpg", text: "Porquerolles is a small island in the Hyères islands, Var, France. It is one of the <a href=\"https://www.nytimes.com/interactive/2017/travel/places-to-visit.html\">52 Places to Go in 2017</a> of the NY Times. The south coast is lined with cliffs, and on the north coast are the port and the beaches. Much of the island is now part of the Port-Cros national park."}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "25", specialCharacter: "+", info: "hours", detail: "of pure problem solving"}
 - {count: "8", specialCharacter: "", info: "speakers", detail: "from country and beyond"}
 - {count: "2", specialCharacter: "", info: "social events", detail: "plus extended lunch breaks"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Igesa School Center"
eventLocationLink: "https://goo.gl/maps/NFdms9EhqiJ2"
eventStreetAddress: "Rue de la Douane"
eventAddressLocality: "Île de Porquerolles"
eventAddressLocalityRegion: "Var"
eventPostalCode: "83400"
eventAddressCountry: "France"
eventStartTime: "2017-09-18T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-09-22T20:00"
eventPlaceCoordinates: "43.000914, 6.204544"
mapCenterCoordinates: "43.000914, 6.204544"
mapMobileCenterCoordinates: "42.000914, 5.204544"

# Venue Block
# https://www.igesa.fr/vos-vacances/recherche-sejour/reserver-mes-vacances/etablissement/porquerolles/
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Igesa School Center"
venueFeatures: ["in the heart of the Port Cros national Park", "at 10 minutes from the beach", "free access activities"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://mailman.i3s.unice.fr/mailman/subscribe/acpss2017-suscribers"
subscribeInfo: "Registration will be open around beginning of March. Number of tickets are limited. Stay tuned!"

# Tickets Block
## TODO
# Instructions for the registration
#
#
# To register, please go to the registration page.
# Please enter the name of an administrative contact person of your organization in the “Contact Name” field, or your name, if you are the person to contact for administrative matters.
#
# Please note: for the early registration fee eligibility, the date of the payment is considered (not the pre-registration date).
## TODO
## Register early to avoid disappointment. Especially, if you require a visa to visit Ireland, please register early, so that formalities can be handled in time.
ticketsTitle: "Pricetable"
ticketsInfo: "<b>Accommodation is included in the registration cost.</b></br>The registration cost also includes teaching materials, lunches and coffee breaks, and organized social events.</br></br><p align=\"left\"><b>Instructions for the registration</b></br>The registration follows a 3 steps hand-shake protocol:</p><ul style=\"text-align: left\"><li>Fill the pre-registration form with personal information (no payment at this point)</li><li>Wait for the confirmation email (this may take a few days, validation is done manually)</li><li>Follow the link given in confirmation e-mail to complete your registration.</li></ul><p align=\"left\">Please enter the name of an administrative contact person of your organization in the “Contact Name” field, or your name, if you are the person to contact for administrative matters. For the early registration fee eligibility, the date of the payment is considered (not the pre-registration date).</br>Register early to avoid disappointment. Especially, if you require a visa to visit France, please register early, so that formalities can be handled in time.</p>"
ticketsEarly: "2017-07-31"
ticketsLate: "2017-09-11"
ticketsOffers:
 -
  name: "Student"
  price: "250"
  priceLate: "300"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  buyButtonLink: "https://www.azur-colloque.fr/DR20/inscription/en"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund."
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-03-17T10:00"
  validThrough: "2017-09-11T23:59"
  disabled: true  
  soldOut: false
  soldOutText: "Sold Out"
 -
  name: "CNRS Student/Employee"
  price: "0"
  priceLate: "NA"
  priceCurrency: "EUR"
  ticketsNumber: "15"
  ribbon: "Free Registration!"
  buyButtonLink: "https://www.azur-colloque.fr/DR20/inscription/en"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid CNRS contract. The travel expenses can be taken in charge by the \"Formation Permanente\"."
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-03-17T10:00"
  validThrough: "2017-09-11T23:59"
  disabled: true
  soldOut: false
  soldOutText: "Sold Out"
 -
  name: "EDSTIC Student"
  price: "200"
  priceLate: "250"
  priceCurrency: "EUR"
  ticketsNumber: "15"
  ribbon: "20%"
  buyButtonLink: "https://www.azur-colloque.fr/DR20/inscription/en"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires to be a PhD student at the IT doctoral school of Nice Sophia Antipolis."
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-03-17T10:00"
  validThrough: "2017-09-11T23:59"
  disabled: true  
  soldOut: false
  soldOutText: "Sold Out"  
 -
  name: "Academic"
  price: "350"
  priceLate: "400"
  priceCurrency: "EUR"
  ticketsNumber: "60"
#  ribbon: "-5%"
  buyButtonLink: "https://www.azur-colloque.fr/DR20/inscription/en"
  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-03-17T10:00"
  validThrough: "2017-09-11T23:59"
  disabled: true
 -
  name: "Industrial"
  price: "600"
  priceLate: "700"
  priceCurrency: "EUR"
  ticketsNumber: "60"
#  ribbon: "-5%"
  buyButtonLink: "https://www.azur-colloque.fr/DR20/inscription/en"
  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-03-17T10:00"
  validThrough: "2017-09-11T23:59"
  disabled: true   
# Footer
socialLinks:
 - {link: "https://plus.google.com/102823071002713900693", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.a4cp.org/", text: "a4cp.org"}
   - {link: "http://gdrro.lip6.fr/", text: "gdrro.lip6.fr"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:acpss2017@i3s.unice.fr", text: "acpss2017@i3s.unice.fr"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "This summer school is co-organized by ACP and the french constraint programming working group for \"Constraints and Operational Research\" within the CNRS research group \"operational research\" (GdR RO). Since 2005, the ACP organizes an international school (Ireland, Canada, Italy, Australia, Poland, Turkey, France). In parallel, the GdR RO also yearly organizes schools on a wide range of research areas covered by the CNRS."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Porquerolles"
directionDetailsCards:
 - {title: "Come with us", information: "Our preferred way: reach the beautiful city of Nice, and let us take care of the transfer to Porquerolles (bus + ferry). Nice Côte d\'Azur Airport is an international airport with excellent traffic connections, and, of course, there is a train station."}
 - {title: "Come by your own", information: 'Reach the ferry terminal La Tour Fondue and then cross the sea. It is a good trip, but easier to prepare for locals. More information will be available on the blog.'}
 - {title: "Living on an island", information: 'Porquerolles is beautiful and welcoming, but it is a small island: be prepared if you have specific needs. Ask to the organizer or contact the <a href=http://www.porquerolles.com/>Porquerolles tourist office</a>.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Airports"
    links:
     - {link: "http://www.nice.aeroport.fr/", text: "www.nice.aeroport.fr"}
     - {link: "http://www.toulon-hyeres.aeroport.fr/", text: "www.toulon-hyeres.aeroport.fr"}
     - {link: "http://www.marseille-airport.com/", text: "www.marseille-airport.com"}
   -
    title: "Others"
    links:
     - {link: "http://www.voyages-sncf.com/", text: "www.voyages-sncf.com (train)"}
     - {link: "http://www.tlv-tvm.com/", text: "Ferries TLV TVM"}
   -
    title: "Porquerolles"
    links:
     - {link: "http://www.porquerolles.com/", text: "www.porquerolles.com"}
     - {link: "http://www.portcrosparcnational.fr", text: "www.portcrosparcnational.fr"}
# Hackathon
hackathonTitle: "Do it yourself!"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Coming soon ..."
hackathonRows:
 - {title: "A great challenge", image: "hackathon-0.png", details: "What better than building its own solver to understand the strengths and weaknesses of our paradigm? This is the challenge we offer this year during the summer school!"}
 - {title: "Learn the insights", image: "hackathon-1.png", details: "From years, observing our students shows us that constraint Programming cannot be reduced to a modelling task. That is to say that an expert of CP cannot be only a good modeler, but he has to understand the underlying mechanics of the CP tools in order to anticipate the difficulties regarding a given problem."}
 - {title: "Improve your software engineering skills", image: "hackathon-1.png", details: "During this week, you'll discover how to build your own CP tool. You'll identify which are the bottlenecks and pitfalls to avoid within the CP tool development, both in terms of algorithmic and software engineering."}


# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "question-mark.png", info: ""}
 - {title: "1nd Place", image: "question-mark.png", info: ""}
 - {title: "3nd Place", image: "question-mark.png", info: ""}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
eventPlaceCoordinates: "43.000914, 6.204544"
mapCenterCoordinates: "43.000914, 6.204544"
mapMobileCenterCoordinates: "43.000914, 6.204544"
