# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "ACPSS 2017"
email: "acpss@i3s.unice.fr"
description: "The ACP summer school is held annually all around the world"
baseurl: "/school2017"
url: "http://school.a4cp.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-45498641-2"
googleAnalyticsSiteUrl: "arnaud-m.github.io"
siteVerification: "09dcT5bQJVjtMrutt2m_aqR5nS9AZ-_RTscjPHuHF10"

# Organizer Info
organizerName: "ACP"
organizerAlternateName: "Association for Constraint Programming"
organizerDescription: "ACP aims at promoting constraint programming in every aspect of the scientific world, by encouraging its theoretical and practical developments, its teachning in the academic institutions, its adoption in the industrial world, and its use in the the application fields."
organizerEmail: "acpss2017@i3s.unice.fr"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.a4cp.org/"

# Head
metaKeywords: "event, summer school, constraint programming, operational research"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: ""
c4sponsorsUrl: "/partnership/"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/diy/", text: "Do It Yourself!"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Buy tickets"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Joint ACP and GdR RO Summer School 2017</br><typeout>"
eventDate: "September 18-22,  2017"
typeoutTextValues: '"", "Constraint Programming", "Operational Research", "Porquerolles, France"'
typeoutFallback: "Constraint Programming"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}
 - {permalink: "/partnership/", text: "Become a sponsor"}
# About Block
aboutTitle: "About the summer school"
aboutBlock:
 - {title: "Topic", image: "OR.jpg", text: "Hybridization of Constraint Programming and Operational Research: from practical opportunities to concrete implementation of solutions." }
# http://sdymchenko.com/blog/2015/03/13/electrifying-eclipse/ 
 - {title: "For which?", image: "electrifying.gif", text: "PhD students, masters students and industrial practitioners, who want to get a good understanding of capabilities and current research directions in the area of Constraint Programming, particularly at the frontier with Operational Research, are all welcome." }
 - {title: "Do it yourself?", image: "minicp.png", text: "minicp competition! The participants will be challenged on a given problem both in term of modeling and implementation of a solution in their own standalone tool." }
 - {title: "1 Place to Go", image: "porquerolles.jpg", text: "Porquerolles is a small island in the Hyères islands, Var, France. It is one of the <a href=\"https://www.nytimes.com/interactive/2017/travel/places-to-visit.html\">52 Places to Go in 2017</a> of the NY Times. The south coast is lined with cliffs, and on the north coast are the port and the beaches. Much of the island is now part of the Port-Cros national park."}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "30", specialCharacter: "+", info: "hours", detail: "of pure problem solving"}
 - {count: "6", specialCharacter: "", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "social events", detail: "plus extended lunch breaks"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Igesa School Center"
eventLocationLink: "https://goo.gl/maps/NFdms9EhqiJ2"
eventStreetAddress: "Rue de la Douane"
eventAddressLocality: "Île de Porquerolles"
eventAddressLocalityRegion: "Var"
eventPostalCode: "83400"
eventAddressCountry: "France"
eventStartTime: "2017-09-18T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-09-22T20:00"
eventPlaceCoordinates: "43.000914, 6.204544"
mapCenterCoordinates: "43.000914, 6.204544"
mapMobileCenterCoordinates: "42.000914, 5.204544"

# Venue Block
# https://www.igesa.fr/vos-vacances/recherche-sejour/reserver-mes-vacances/etablissement/porquerolles/
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Igesa School Center"
venueFeatures: ["in the heart of the Port Cros national Park"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates (soon)"
subscribeAction: ""
subscribeInfo: "Registration will be open around beginning of March. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "<b>Registration cost are not yet fixed.</b> Registration will be open around beginning of March. Accommodation is included in the registration cost. The registration cost includes teaching materials, lunches and coffee breaks, and organized social events."
ticketsOffers:
 -
  name: "Student"
  price: "?"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  buyButtonLink: ""
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-03-01T10:00"
  validThrough: "2017-09-14T23:59"
  disabled: true  
#  soldOut: true
#  soldOutText: "Sold Out"
 -
  name: "CNRS Student/Employee"
  price: "0"
  priceCurrency: "EUR"
  ticketsNumber: "10"
  ribbon: "Free Registration!"
  buyButtonLink: ""
  buyButtonText: "Buy Now"
  additionalInfo: "The school has been awarded the \"École Thématique\" label of the CNRS."
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-03-01T10:00"
  validThrough: "2017-09-14T23:59"
  disabled: true  
#  soldOut: true
#  soldOutText: "Sold Out"  
 -
  name: "Early Bird"
  price: "?"
  priceCurrency: "EUR"
  ticketsNumber: "60"
#  ribbon: "-5%"
  buyButtonLink: ""
  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-03-01T10:00"
  validThrough: "2017-09-04T23:59"
  disabled: true  
 -
  name: "Last Chance"
  price: "?"
  priceCurrency: "EUR"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: ""
  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-09-05T00:00"
  validThrough: "2017-09-14T23:59"
  disabled: true

# Footer
socialLinks:
 - {link: "https://plus.google.com/102823071002713900693", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.a4cp.org/", text: "a4cp.org"}
   - {link: "http://gdrro.lip6.fr/", text: "gdrro.lip6.fr"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:acpss2017@i3s.unice.fr", text: "acpss2017@i3s.unice.fr"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "This summer school is co-organized by ACP and the french constraint programming working group for \"Constraints and Operational Research\" within the CNRS research group \"operational research\" (GdR RO). Since 2005, the ACP organizes an international school (Ireland, Canada, Italy, Australia, Poland, Turkey, France). In parallel, the GdR RO also yearly organizes schools on a wide range of research areas covered by the CNRS."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Porquerolles"
directionDetailsCards:
 - {title: "Come with us", information: "Our preferred way: reach the beautiful city of Nice, and let us take care of the transfer to Porquerolles (bus + ferry). Nice Côte d\'Azur Airport is an international airport with excellent traffic connections, and, of course, there is a train station."}
 - {title: "Come by your own", information: 'Reach the ferry terminal La Tour Fondue and then cross the sea. It is a good trip, but easier to prepare for locals. More information will be available on the blog.'}
 - {title: "Living on an island", information: 'Porquerolles is beautiful and welcoming, but it is a small island: be prepared if you have specific needs. Ask to the organizer or contact the <a href=http://www.porquerolles.com/>Porquerolles tourist office</a>.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Airports"
    links:
     - {link: "http://www.nice.aeroport.fr/", text: "www.nice.aeroport.fr"}
     - {link: "http://www.toulon-hyeres.aeroport.fr/", text: "www.toulon-hyeres.aeroport.fr"}
     - {link: "http://www.marseille-airport.com/", text: "www.marseille-airport.com"}
   -
    title: "Others"
    links:
     - {link: "http://www.voyages-sncf.com/", text: "www.voyages-sncf.com (train)"}
     - {link: "http://www.tlv-tvm.com/", text: "Ferries TLV TVM"}
   -
    title: "Porquerolles"
    links:
     - {link: "http://www.porquerolles.com/", text: "www.porquerolles.com"}
     - {link: "http://www.portcrosparcnational.fr", text: "www.portcrosparcnational.fr"}
# Hackathon
hackathonTitle: "Do it yourself!"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Coming soon ..."
hackathonRows:
 - {title: "A", image: "hackathon-0.png", details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quam nunc, euismod sed diam ut, malesuada gravida lectus. Mauris sed pharetra massa. Fusce id metus massa. Sed faucibus odio in sollicitudin pretium. Aenean eu magna ligula."}
 - {title: "B", image: "hackathon-1.png", details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quam nunc, euismod sed diam ut, malesuada gravida lectus. Mauris sed pharetra massa. Fusce id metus massa. Sed faucibus odio in sollicitudin pretium. Aenean eu magna ligula."}


# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "question-mark.png", info: ""}
 - {title: "1nd Place", image: "question-mark.png", info: ""}
 - {title: "3nd Place", image: "question-mark.png", info: ""}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
eventPlaceCoordinates: "43.000914, 6.204544"
mapCenterCoordinates: "43.000914, 6.204544"
mapMobileCenterCoordinates: "43.000914, 6.204544"
